### ISSUE TITLE
Mac OS ARM: Ai model not downloading / being saved

### ISSUE THREAD

**Issue by mistuk72** [Steffenhir/GraXpert#102]
Using the Mac OS ARM latest version the AI model doesn't seem to be being downloaded or saved in the right place. Using the console window in PixInsight I get the following....

`2023-11-28 12:38:51,445 MainProcess root INFO     using AI version 1.0.1. you can change this by providing the argument '-ai_version'

2023-11-28 12:38:51,796 MainProcess root ERROR    Traceback (most recent call last):
2023-11-28 12:38:51,796 MainProcess root ERROR      File "graxpert/main.py", line 127, in 
2023-11-28 12:38:51,796 MainProcess root ERROR      File "graxpert/main.py", line 119, in main

2023-11-28 12:38:51,796 MainProcess root ERROR      File "graxpert/CommandLineTool.py", line 59, in execute
2023-11-28 12:38:51,796 MainProcess root ERROR      File "graxpert/background_extraction.py", line 70, in extract_background
2023-11-28 12:38:51,796 MainProcess root ERROR      File "keras/src/saving/saving_api.py", line 238, in load_model
2023-11-28 12:38:51,796 MainProcess root ERROR      File "keras/src/utils/traceback_utils.py", line 70, in error_handler
2023-11-28 12:38:51,796 MainProcess root ERROR      File "keras/src/utils/traceback_utils.py", line 65, in error_handler
2023-11-28 12:38:51,796 MainProcess root ERROR      File "keras/src/saving/legacy/save.py", line 234, in load_model
2023-11-28 12:38:51,797 MainProcess root ERROR    OSError
2023-11-28 12:38:51,797 MainProcess root ERROR    :
2023-11-28 12:38:51,797 MainProcess root ERROR    No file or directory found at /Users/kevinmorgan/Library/Application Support/GraXpert/ai-models/1.0.1/bg_model
[71205] Failed to execute script 'main' due to unhandled exception: No file or directory found at /Users/kevinmorgan/Library/Application Support/GraXpert/ai-models/1.0.1/bg_model
[71205] Traceback:
Traceback (most recent call last):
  File "graxpert/main.py", line 127, in 
  File "graxpert/main.py", line 119, in main
  File "graxpert/CommandLineTool.py", line 59, in execute
  File "graxpert/background_extraction.py", line 70, in extract_background
  File "keras/src/saving/saving_api.py", line 238, in load_model
  File "keras/src/utils/traceback_utils.py", line 70, in error_handler
  File "keras/src/utils/traceback_utils.py", line 65, in error_handler
  File "keras/src/saving/legacy/save.py", line 234, in load_model
OSError: No file or directory found at /Users/kevinmorgan/Library/Application Support/GraXpert/ai-models/1.0.1/bg_model`

Doesn't seem to work in standalone mode either - but not sure where to get logs for that

**Comment by mistuk72** [comment]
Did complete re-install now working. Possible user error
