### ISSUE TITLE
Just a grey screen that has CTk at the top and spinning wheel

### ISSUE THREAD

**Issue by whyf16uy** [Steffenhir/GraXpert#141]
M2 mac mini 16 gigs ram Sonoma 14.4.1
2.0 ran flawless
Log-
2024-04-04 18:52:55,103 MainProcess tensorflow WARNING  AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
2024-04-04 18:52:57,864 MainProcess root WARNING  WARNING: could not calculate monitor dpi, unsupported operand type(s) for /: 'NoneType' and 'float'
2024-04-04 18:53:11,376 SpawnProcess-2 root INFO     stretch.stretch_channel started
2024-04-04 18:53:11,385 SpawnProcess-3 root INFO     stretch.stretch_channel started
2024-04-04 18:53:11,403 SpawnProcess-4 root INFO     stretch.stretch_channel started
2024-04-04 18:53:11,818 SpawnProcess-2 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:11,867 SpawnProcess-3 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:11,878 SpawnProcess-4 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:21,846 MainProcess absl INFO     Fingerprint not found. Saved model loading will continue.
2024-04-04 18:53:21,952 MainProcess tensorflow WARNING  No training configuration found in save file, so the model was *not* compiled. Compile it manually.
2024-04-04 18:53:22,101 MainProcess root ERROR    skimage/_shared/utils.py:293: RuntimeWarning: Images with dimensions (M, N, 3) are interpreted as 2D+RGB by default. Use `multichannel=False` to interpret as 3D image with last dimension of length 3.
2024-04-04 18:53:22,980 MainProcess root ERROR    WARNING
2024-04-04 18:53:22,980 MainProcess root ERROR    : VerifyWarning: Keyword name 'SMOOTHING' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [unknown]
2024-04-04 18:53:22,467 MainProcess astropy WARNING  VerifyWarning: Keyword name 'SMOOTHING' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
2024-04-04 18:53:22,998 MainProcess root ERROR    WARNING
2024-04-04 18:53:22,999 MainProcess root ERROR    : VerifyWarning: Keyword name 'CORR-TYPE' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [unknown]
2024-04-04 18:53:22,998 MainProcess astropy WARNING  VerifyWarning: Keyword name 'CORR-TYPE' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
2024-04-04 18:53:23,048 SpawnProcess-2 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,048 SpawnProcess-2 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,048 SpawnProcess-3 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,048 SpawnProcess-3 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,048 SpawnProcess-4 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,048 SpawnProcess-4 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,596 SpawnProcess-2 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,596 SpawnProcess-2 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,622 SpawnProcess-4 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,622 SpawnProcess-4 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,651 SpawnProcess-3 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,651 SpawnProcess-3 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:23,830 SpawnProcess-5 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,864 SpawnProcess-6 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,902 SpawnProcess-7 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,963 SpawnProcess-10 root INFO     stretch.stretch_channel started
2024-04-04 18:53:23,994 SpawnProcess-8 root INFO     stretch.stretch_channel started
2024-04-04 18:53:24,030 SpawnProcess-9 root INFO     stretch.stretch_channel started
2024-04-04 18:53:24,331 SpawnProcess-10 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:24,366 SpawnProcess-8 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:24,404 SpawnProcess-9 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:24,429 SpawnProcess-5 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:24,446 SpawnProcess-6 root INFO     stretch.stretch_channel finished
2024-04-04 18:53:24,447 SpawnProcess-7 root INFO     stretch.stretch_channel finished
2024-04-23 11:07:22,351 MainProcess urllib3.connectionpool WARNING  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x11a62f310>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')': /graxpert-bge-ai-onnx?location=
2024-04-23 11:08:37,752 MainProcess urllib3.connectionpool WARNING  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f2a90>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')': /graxpert-bge-ai-onnx?location=
2024-04-23 11:09:53,574 MainProcess urllib3.connectionpool WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f2090>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')': /graxpert-bge-ai-onnx?location=
2024-04-23 11:11:10,180 MainProcess urllib3.connectionpool WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f3c10>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')': /graxpert-bge-ai-onnx?location=
2024-04-23 11:12:28,386 MainProcess urllib3.connectionpool WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f8610>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')': /graxpert-bge-ai-onnx?location=
2024-04-23 11:13:43,392 MainProcess root ERROR    HTTPSConnectionPool(host='minio.schmelly.de', port=443): Max retries exceeded with url: /graxpert-bge-ai-onnx?location= (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f9050>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)'))
Traceback (most recent call last):
  File "urllib3/connection.py", line 203, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
TimeoutError: [Errno 60] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1096, in _validate_conn
  File "urllib3/connection.py", line 611, in connect
  File "urllib3/connection.py", line 212, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x13f4f9050>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "graxpert/ai_model_handling.py", line 47, in list_remote_versions
  File "minio/api.py", line 3105, in _list_objects
  File "minio/api.py", line 431, in _execute
  File "minio/api.py", line 488, in _get_region
  File "minio/api.py", line 296, in _url_open
  File "urllib3/poolmanager.py", line 444, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  File "urllib3/connectionpool.py", line 874, in urlopen
  [Previous line repeated 2 more times]
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='minio.schmelly.de', port=443): Max retries exceeded with url: /graxpert-bge-ai-onnx?location= (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13f4f9050>, 'Connection to minio.schmelly.de timed out. (connect timeout=300)'))

**Comment by schmelly** [comment]
Hi,

your log indicates GraXpert could not reach our server which is serving the ai models. As the server is up and running please try again and double check no anti malware functions are blocking GraXpert.

CS, David

**Comment by whyf16uy** [comment]
Thanks for putting me on the right track. I use PaloAlto Global Protect VPN for work. Usually have it turned off. Turned it on and ran Graxpert. Started right up and worked perfectly. Must be a setting on my local firewall that I need to dig into. Did work with the older AI version though.
Thanks again and I guess we can close this issue.
