### ISSUE TITLE
No AI models, S3 host down?

### ISSUE THREAD

**Issue by wizzlebippi** [Steffenhir/GraXpert#160]
Just updated GraXpert and went to download new AI models.  GraXpert takes several minutes to open, appearing frozen at a white window, and presents no dropdown menus to select AI models.  Tried solution in #136 and can't access www.schmelly.de.  Tried from phone disconnected from my home network and still can't access www.schmelly.de.

**Comment by AndySomnifac** [comment]
I am having the experience. 2 machines on my local network (one Win10 and one Win11), computer time correct on both, can't access www,schmelly.de on either. Mobile device on a mobile data connection (not on my local network also cannot access www.schmelly.de. The result is EEE_CONNECTION_REFUSED.

**Comment by JayTee33** [comment]
I'm having the same issue - no AI models available. checking the log I see:

2024-06-02 03:10:53,550 MainProcess root ERROR    HTTPSConnectionPool(host='minio.schmelly.de', port=443): Max retries exceeded with url: /graxpert-bge-ai-onnx?location= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000224F16DD9C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

Same issue on two machines. Same error appears when running from PixInsight.

**Comment by daveswin** [comment]
Also have the same issue on a Kubuntu box.  Worked fine this morning and didn't after lunch...

**Comment by schmelly** [comment]
Hi guys,

thanks for reporting. I can confirm we had a service outtage and it should be available again. Please re-open if you still have issues.

CS, David
