### ISSUE TITLE
source build fails: No module named 'graxpert.s3_secrets'

### ISSUE THREAD

**Issue by stevelcb** [Steffenhir/GraXpert#167]
Hi
I built GraXpert but get the above following error. Here's the output from within the env:

```

(graxpert-env) steve@cocina:~/GraXpert$ python -m graxpert.main
ERROR:root:No module named 'graxpert.s3_secrets'
Traceback (most recent call last):
  File "/home/steve/GraXpert/graxpert/ai_model_handling.py", line 13, in <module>
    from graxpert.s3_secrets import endpoint, ro_access_key, ro_secret_key
ModuleNotFoundError: No module named 'graxpert.s3_secrets'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/steve/GraXpert/graxpert/main.py", line 20, in <module>
    from graxpert.s3_secrets import bge_bucket_name, denoise_bucket_name
ModuleNotFoundError: No module named 'graxpert.s3_secrets'
(graxpert-env) steve@cocina:~/GraXpert$ 
```
Any ideas?
TIA

**Comment by schmelly** [comment]
Hi Steve,

we do not push that file to git to reduce the likelyhood of automated attacks against our object storage that holds the ml models (crawlers will find those). Please contact us on Discord where I can provide that file to you (`support` channel in the `GRAXPERT & CO` tree): https://discord.gg/darkmatters

CS, David

**Comment by imaluschi** [comment]
This seems to be a common Issue, exactly the same problem here.

**Comment by imaluschi** [comment]
Found a solution here:
https://astroisk.nl/installing-graxpert-on-raspberry-pi-5/
`nano ./graxpert/s3_secrets.py`
Fill it with
`endpoint = ""
ro_access_key = ""
ro_secret_key = ""
bucket_name = ""
bge_bucket_name = ""
denoise_bucket_name = ""`
Thats it.

Why not resolving commonly? At least update the Readme? That would have saved a lot of useless time trying and searching to solve the problem.

**Comment by d33psky** [comment]
recent code requires 2 more buckets :
```
cat > graxpert/s3_secrets.py <<EOF
endpoint = ""
ro_access_key = ""
ro_secret_key = ""
bucket_name = ""
bge_bucket_name = ""
denoise_bucket_name = ""
deconvolution_object_bucket_name = ""
deconvolution_stars_bucket_name = ""
EOF
```

as well as another candidate for the requirements file
```
pip install onnxruntime
```

and on Ubuntu also this
```
sudo apt install python3-tk
```
to make `import tkinter` work.
