### ISSUE TITLE
Mac AI models 3.x fail - Error compiling model

### ISSUE THREAD

**Issue by notnicehat** [Steffenhir/GraXpert#178]
Mac user here with version 3.0.2 - attempting to use any of the 3.x Denoise AI models (3.0.0, 3.0.1, 3.0.2) result in an error. I can use the 2.x AI models for denoise, but I'm not sure why it's not working. I cleared the 3.x models out and ran a denoise which downloaded the 3.0.2 model then attempted to denoise and fails. 

Screenshot of the ~/Library/ApplicationSupport/GraXpert/denoise-ai-models folder - model.onnx is present
![Screenshot 2024-07-03 at 12 29 27 PM](https://github.com/Steffenhir/GraXpert/assets/8051939/b7d82189-7f40-4bce-aedb-e0faf3d81da0)

Log included - I selected 3.0.2 and it downloads the new model and fails upon denoising:
[graxpert.log](https://github.com/user-attachments/files/16089960/graxpert.log)

2024-07-03 12:26:27,315 MainProcess root INFO     Progress: 100%
2024-07-03 12:26:28,873 MainProcess root INFO     Starting denoising
2024-07-03 12:26:30,099
 MainProcess root ERROR    [ONNXRuntimeError] : 1 : FAIL : Error compiling model: compiler error: Espresso exception: "Invalid blob shape": generic_elementwise_kernel: cannot broadcast:
	(1, 300, 1, 1)
	(1, 123, 1, 1)
Traceback (most recent call last):
  File "graxpert/application/app.py", line 350, in on_denoise_request
  File "graxpert/denoising.py", line 70, in denoise
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 483, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Error compiling model: compiler error: Espresso exception: "Invalid blob shape": generic_elementwise_kernel: cannot broadcast:
	(1, 300, 1, 1)
	(1, 123, 1, 1)

**Comment by linudaar** [comment]
Same here. Mac, Sonoma, AMD64. v3.x models return the same error. v2.x models work.

**Comment by notnicehat** [comment]
> Hi, just chiming in. I get the same issue but I think it might be with the GPU acceleration of the AI models, rather than the models themselves? So if you disable the `AI Hardware Acceleration` toggle you can get the 3.0.2 models working without the error (at least that worked for me, YMMV).
> <img alt="image" width="254" src="https://private-user-images.githubusercontent.com/105242/374846933-24798676-ef23-4288-922c-5c7f4ea50686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjkzNzgsIm5iZiI6MTcyODYyOTA3OCwicGF0aCI6Ii8xMDUyNDIvMzc0ODQ2OTMzLTI0Nzk4Njc2LWVmMjMtNDI4OC05MjJjLTVjN2Y0ZWE1MDY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNjQ0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTg5MDQwZjQ2YjJiYmQwMTk0NmZlMWNhMjYzMzI4N2FhNjViODkwNThmZWZlZjA0YTQyNWUxNzYwNDkxOGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.srDLkXE9_BDYfyKqFi0_Dz0pxCUK9FNwyI-JeyudtZQ">
> 
> (In case it's relevant, AMD64 + Mac Sonoma 14.6.1)

Unchecking the "Enable Acceleration" toggle worked! thank you. the 3.0.2 model does work better but without the hardware acceleration it is at least twice as slow. Guess I need to buy some apple silicon. 

Not sure if this should be marked as resolved - at the very least it requires a note or an update to the error message.

**Comment by mikegeyser** [comment]
Thanks for checking and confirming. 😁 

After getting it working, I don't see very much improvement in the 3.0 models over the 2.0 models. I'm not sure why, but the result that I get when running denoise aggressively is a far cry from what others are experiencing. At full strength I get maybe a small incremental improvement in noise.

- [Cuiv, the lazy geek (so via pixinsight plugin)](https://www.youtube.com/watch?v=8MiyLU1w91Y&ab_channel=Cuiv%2CTheLazyGeek)
- [Deep space astro (so using the standalone app)](https://www.youtube.com/watch?v=OmHBvWwU6zE&t=316s&ab_channel=DeepSpaceAstro)

The commonality above is windows... So I'd love to know if anyone is getting these kinds of dramatic results using mac, and if so what I'm doing wrong.

(Just to be crystal clear, I totally understand that this is a personal/hobby project for the maintainers and don't feel any entitlement. Fixing this for Mac is likely not a priority, I just don't have a windows machine and would love to join the fun with this excellent tool.)

**Original**
![Original](https://github.com/user-attachments/assets/78980b29-2be1-47aa-9c25-53a07b6dc051)

**Denoised at full strength**
![Denoised at full strength](https://github.com/user-attachments/assets/7785eaf1-e0a6-42ca-9380-4618e43ac2dc)
