### ISSUE TITLE
Missing model files

### ISSUE THREAD

**Issue by WillPwn4Food** [Steffenhir/GraXpert#192]
Hello, I just downloaded and installed the latest windows package to update and now it seems like the model.onnx files are missing. I've done a repair, but no difference. I've opened up the directory and they seem fairly bare.

Here's the actual error:
`cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "graxpert\main.py", line 298, in <module>
  File "graxpert\main.py", line 278, in main
  File "D:\a\GraXpert\GraXpert\graxpert\cmdline_tools.py", line 153, in execute
  File "D:\a\GraXpert\GraXpert\graxpert\background_extraction.py", line 75, in extract_background
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\Ivan\AppData\Local\GraXpert\GraXpert\bge-ai-models\1.0.1\model.onnx failed:Load model C:\Users\Ivan\AppData\Local\GraXpert\GraXpert\bge-ai-models\1.0.1\model.onnx failed. File doesn't exist`

**Comment by WillPwn4Food** [comment]
I should say I'm trying to run the GraXpert PI script in the Toolbox folder from this source (https://www.ideviceapps.de/PixInsight/Utilities/)

**Comment by WillPwn4Food** [comment]
Ok, so if I open GraXpert the windows app and try to use the models, it will download them, just not via the script, got it working.
