### ISSUE TITLE
Denoise Error

### ISSUE THREAD

**Issue by astrozag** [Steffenhir/GraXpert#195]
Hi,

When I denoise on any model version I get the following error. Any advice?

2024-10-13 22:39:11,691 MainProcess root INFO     Starting denoising
2024-10-13 22:39:17,701 MainProcess root INFO     Available inference providers : ['DmlExecutionProvider', 'CPUExecutionProvider']
2024-10-13 22:39:17,701 MainProcess root INFO     Used inference providers : ['DmlExecutionProvider', 'CPUExecutionProvider']
2024-10-13 22:39:19,124 MainProcess root ERROR    [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/encoders.0/encoders.0.0/Mul_8' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2571)\onnxruntime_pybind11_state.pyd!00007FFD9EDBE0E8: (caller: 00007FFD9F5456D1) Exception(11) tid(19e8) 8007000E Not enough memory resources are available to complete this operation.

Traceback (most recent call last):
  File "D:\a\GraXpert\GraXpert\graxpert\application\app.py", line 350, in on_denoise_request
  File "D:\a\GraXpert\GraXpert\graxpert\denoising.py", line 118, in denoise
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 220, in run
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'/encoders.0/encoders.0.0/Mul_8' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2571)\onnxruntime_pybind11_state.pyd!00007FFD9EDBE0E8: (caller: 00007FFD9F5456D1) Exception(11) tid(19e8) 8007000E Not enough memory resources are available to complete this operation.

My laptop isn't top spec at all but before I go buy a new one, and I think it's a RAM error? If so, what size RAM is adequate for GraXpert?

Processor	  AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx     2.50 GHz
Installed RAM	  4.00 GB (3.46 GB usable)
System              Windows 10 Home
System type	  64-bit operating system, x64-based processor

**Comment by astrozag** [comment]
Thanks. It worked.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
