### ISSUE TITLE
AI not working on windows 11 with latest version "ariel"

### ISSUE THREAD

**Issue by LEMIR13** [Steffenhir/GraXpert#98]
I dowloaded the latest version of Graxpert 2.0.2

 The program downloaded the AI but then it doesn't work.

![Capture d'écran 2023-11-11 082154](https://github.com/Steffenhir/GraXpert/assets/48150305/00139c55-aa88-4484-9ba7-d8ba6e247098)

I can't find the log files despite the path on the screen...

**Comment by Steffenhir** [comment]
Hi, does this happen with every image, or just with a particular one?

**Comment by LEMIR13** [comment]
With every images

**Comment by Steffenhir** [comment]
Without the log file it is hard to find out what went wrong. Do you have trouble finding the appdata folder or is there no Graxpert folder inside appdata\local ? If you have trouble finding the appdata folder, you can follow this tutorial https://www.howtogeek.com/885078/cant-find-appdata-folder-on-windows-11-how-to-get-it-back/

**Comment by LEMIR13** [comment]
Thanks for the help !
I just find the log with this tutorial. 

Here's the log:
[graxpert.log](https://github.com/Steffenhir/GraXpert/files/13328083/graxpert.log)

**Comment by LEMIR13** [comment]
any idea of the problem ?

**Comment by LEMIR13** [comment]
I tried 2.02, 2.01, 2.0, they doesn't worf for me.

Release "Dione" 1.0.6cAI is working

**Comment by Steffenhir** [comment]
Could you try to delete the GraXpert directory located at YOURUSERNAME/AppData/Local ? When you start the AI method again afterwards, the AI model should be downloaded again.

**Comment by LEMIR13** [comment]
I did it, the app downloaded the AI, but then it didn't worked...
![image](https://github.com/Steffenhir/GraXpert/assets/48150305/646d2c8d-e55d-4b8c-bb71-ebddf9772396)


Here's the log. I tried to shutdown and reload, didn't worked.

2023-11-22 21:31:47,058 MainProcess root INFO     C:\Users\Rémi MAGAN\AppData\Local\GraXpert\GraXpert\preferences.json appears to be missing. it will be created after program shutdown
2023-11-22 21:31:47,743 MainProcess root INFO     C:\Users\Rémi MAGAN\AppData\Local\GraXpert\GraXpert\preferences.json appears to be missing. it will be created after program shutdown
2023-11-22 21:31:48,413 MainProcess pyi_splash INFO     A connection to the splash screen was successfully established.
2023-11-22 21:33:42,382 SpawnProcess-4 root INFO     stretch.stretch_channel started
2023-11-22 21:33:42,392 SpawnProcess-3 root INFO     stretch.stretch_channel started
2023-11-22 21:33:42,397 SpawnProcess-2 root INFO     stretch.stretch_channel started
2023-11-22 21:33:42,618 SpawnProcess-4 root INFO     stretch.stretch_channel finished
2023-11-22 21:33:42,643 SpawnProcess-3 root INFO     stretch.stretch_channel finished
2023-11-22 21:33:42,646 SpawnProcess-2 root INFO     stretch.stretch_channel finished
2023-11-22 21:33:53,956 MainProcess root INFO     Progress: 0%
2023-11-22 21:33:54,081 MainProcess root INFO     Progress: 1%
2023-11-22 21:33:54,170 MainProcess root INFO     Progress: 1%
2023-11-22 21:33:54,298 MainProcess root INFO     Progress: 2%
2023-11-22 21:33:54,384 MainProcess root INFO     Progress: 2%
2023-11-22 21:33:54,510 MainProcess root INFO     Progress: 3%
2023-11-22 21:33:54,598 MainProcess root INFO     Progress: 3%
2023-11-22 21:33:54,764 MainProcess root INFO     Progress: 4%
2023-11-22 21:33:54,883 MainProcess root INFO     Progress: 4%
2023-11-22 21:33:55,039 MainProcess root INFO     Progress: 5%
2023-11-22 21:33:55,161 MainProcess root INFO     Progress: 5%
2023-11-22 21:33:55,282 MainProcess root INFO     Progress: 6%
2023-11-22 21:33:55,442 MainProcess root INFO     Progress: 6%
2023-11-22 21:33:55,562 MainProcess root INFO     Progress: 7%
2023-11-22 21:33:55,682 MainProcess root INFO     Progress: 7%
2023-11-22 21:33:55,805 MainProcess root INFO     Progress: 8%
2023-11-22 21:33:55,929 MainProcess root INFO     Progress: 8%
2023-11-22 21:33:56,049 MainProcess root INFO     Progress: 9%
2023-11-22 21:33:56,169 MainProcess root INFO     Progress: 9%
2023-11-22 21:33:56,292 MainProcess root INFO     Progress: 10%
2023-11-22 21:33:56,412 MainProcess root INFO     Progress: 10%
2023-11-22 21:33:56,532 MainProcess root INFO     Progress: 11%
2023-11-22 21:33:56,653 MainProcess root INFO     Progress: 11%
2023-11-22 21:33:56,774 MainProcess root INFO     Progress: 12%
2023-11-22 21:33:56,902 MainProcess root INFO     Progress: 12%
2023-11-22 21:33:57,008 MainProcess root INFO     Progress: 13%
2023-11-22 21:33:57,116 MainProcess root INFO     Progress: 14%
2023-11-22 21:33:57,230 MainProcess root INFO     Progress: 14%
2023-11-22 21:33:57,389 MainProcess root INFO     Progress: 15%
2023-11-22 21:33:57,547 MainProcess root INFO     Progress: 15%
2023-11-22 21:33:57,708 MainProcess root INFO     Progress: 16%
2023-11-22 21:33:57,869 MainProcess root INFO     Progress: 16%
2023-11-22 21:33:58,029 MainProcess root INFO     Progress: 17%
2023-11-22 21:33:58,152 MainProcess root INFO     Progress: 17%
2023-11-22 21:33:58,309 MainProcess root INFO     Progress: 18%
2023-11-22 21:33:58,469 MainProcess root INFO     Progress: 18%
2023-11-22 21:33:58,629 MainProcess root INFO     Progress: 19%
2023-11-22 21:33:58,824 MainProcess root INFO     Progress: 19%
2023-11-22 21:33:59,019 MainProcess root INFO     Progress: 20%
2023-11-22 21:33:59,211 MainProcess root INFO     Progress: 20%
2023-11-22 21:33:59,408 MainProcess root INFO     Progress: 21%
2023-11-22 21:33:59,608 MainProcess root INFO     Progress: 21%
2023-11-22 21:33:59,774 MainProcess root INFO     Progress: 22%
2023-11-22 21:33:59,969 MainProcess root INFO     Progress: 22%
2023-11-22 21:34:00,169 MainProcess root INFO     Progress: 23%
2023-11-22 21:34:00,328 MainProcess root INFO     Progress: 23%
2023-11-22 21:34:00,523 MainProcess root INFO     Progress: 24%
2023-11-22 21:34:00,681 MainProcess root INFO     Progress: 24%
2023-11-22 21:34:00,912 MainProcess root INFO     Progress: 25%
2023-11-22 21:34:01,143 MainProcess root INFO     Progress: 25%
2023-11-22 21:34:01,377 MainProcess root INFO     Progress: 26%
2023-11-22 21:34:01,613 MainProcess root INFO     Progress: 26%
2023-11-22 21:34:01,843 MainProcess root INFO     Progress: 27%
2023-11-22 21:34:02,036 MainProcess root INFO     Progress: 28%
2023-11-22 21:34:02,225 MainProcess root INFO     Progress: 28%
2023-11-22 21:34:02,445 MainProcess root INFO     Progress: 29%
2023-11-22 21:34:02,638 MainProcess root INFO     Progress: 29%
2023-11-22 21:34:02,831 MainProcess root INFO     Progress: 30%
2023-11-22 21:34:03,020 MainProcess root INFO     Progress: 30%
2023-11-22 21:34:03,209 MainProcess root INFO     Progress: 31%
2023-11-22 21:34:03,387 MainProcess root INFO     Progress: 31%
2023-11-22 21:34:03,578 MainProcess root INFO     Progress: 32%
2023-11-22 21:34:03,748 MainProcess root INFO     Progress: 32%
2023-11-22 21:34:03,919 MainProcess root INFO     Progress: 33%
2023-11-22 21:34:04,093 MainProcess root INFO     Progress: 33%
2023-11-22 21:34:04,261 MainProcess root INFO     Progress: 34%
2023-11-22 21:34:04,432 MainProcess root INFO     Progress: 34%
2023-11-22 21:34:04,608 MainProcess root INFO     Progress: 35%
2023-11-22 21:34:04,762 MainProcess root INFO     Progress: 35%
2023-11-22 21:34:04,921 MainProcess root INFO     Progress: 36%
2023-11-22 21:34:05,073 MainProcess root INFO     Progress: 36%
2023-11-22 21:34:05,268 MainProcess root INFO     Progress: 37%
2023-11-22 21:34:05,429 MainProcess root INFO     Progress: 37%
2023-11-22 21:34:05,585 MainProcess root INFO     Progress: 38%
2023-11-22 21:34:05,748 MainProcess root INFO     Progress: 38%
2023-11-22 21:34:05,907 MainProcess root INFO     Progress: 39%
2023-11-22 21:34:06,068 MainProcess root INFO     Progress: 39%
2023-11-22 21:34:06,187 MainProcess root INFO     Progress: 40%
2023-11-22 21:34:06,346 MainProcess root INFO     Progress: 40%
2023-11-22 21:34:06,502 MainProcess root INFO     Progress: 41%
2023-11-22 21:34:06,663 MainProcess root INFO     Progress: 42%
2023-11-22 21:34:06,783 MainProcess root INFO     Progress: 42%
2023-11-22 21:34:06,944 MainProcess root INFO     Progress: 43%
2023-11-22 21:34:07,108 MainProcess root INFO     Progress: 43%
2023-11-22 21:34:07,229 MainProcess root INFO     Progress: 44%
2023-11-22 21:34:07,388 MainProcess root INFO     Progress: 44%
2023-11-22 21:34:07,547 MainProcess root INFO     Progress: 45%
2023-11-22 21:34:07,668 MainProcess root INFO     Progress: 45%
2023-11-22 21:34:07,791 MainProcess root INFO     Progress: 46%
2023-11-22 21:34:07,956 MainProcess root INFO     Progress: 46%
2023-11-22 21:34:08,077 MainProcess root INFO     Progress: 47%
2023-11-22 21:34:08,234 MainProcess root INFO     Progress: 47%
2023-11-22 21:34:08,360 MainProcess root INFO     Progress: 48%
2023-11-22 21:34:08,477 MainProcess root INFO     Progress: 48%
2023-11-22 21:34:08,623 MainProcess root INFO     Progress: 49%
2023-11-22 21:34:08,751 MainProcess root INFO     Progress: 49%
2023-11-22 21:34:08,866 MainProcess root INFO     Progress: 50%
2023-11-22 21:34:08,984 MainProcess root INFO     Progress: 50%
2023-11-22 21:34:09,106 MainProcess root INFO     Progress: 51%
2023-11-22 21:34:09,262 MainProcess root INFO     Progress: 51%
2023-11-22 21:34:09,381 MainProcess root INFO     Progress: 52%
2023-11-22 21:34:09,494 MainProcess root INFO     Progress: 52%
2023-11-22 21:34:09,624 MainProcess root INFO     Progress: 53%
2023-11-22 21:34:09,741 MainProcess root INFO     Progress: 53%
2023-11-22 21:34:09,859 MainProcess root INFO     Progress: 54%
2023-11-22 21:34:09,976 MainProcess root INFO     Progress: 55%
2023-11-22 21:34:10,097 MainProcess root INFO     Progress: 55%
2023-11-22 21:34:10,257 MainProcess root INFO     Progress: 56%
2023-11-22 21:34:10,458 MainProcess root INFO     Progress: 56%
2023-11-22 21:34:10,618 MainProcess root INFO     Progress: 57%
2023-11-22 21:34:10,776 MainProcess root INFO     Progress: 57%
2023-11-22 21:34:10,935 MainProcess root INFO     Progress: 58%
2023-11-22 21:34:11,092 MainProcess root INFO     Progress: 58%
2023-11-22 21:34:11,214 MainProcess root INFO     Progress: 59%
2023-11-22 21:34:11,373 MainProcess root INFO     Progress: 59%
2023-11-22 21:34:11,533 MainProcess root INFO     Progress: 60%
2023-11-22 21:34:11,652 MainProcess root INFO     Progress: 60%
2023-11-22 21:34:11,814 MainProcess root INFO     Progress: 61%
2023-11-22 21:34:11,936 MainProcess root INFO     Progress: 61%
2023-11-22 21:34:12,099 MainProcess root INFO     Progress: 62%
2023-11-22 21:34:12,222 MainProcess root INFO     Progress: 62%
2023-11-22 21:34:12,344 MainProcess root INFO     Progress: 63%
2023-11-22 21:34:12,467 MainProcess root INFO     Progress: 63%
2023-11-22 21:34:12,624 MainProcess root INFO     Progress: 64%
2023-11-22 21:34:12,749 MainProcess root INFO     Progress: 64%
2023-11-22 21:34:12,872 MainProcess root INFO     Progress: 65%
2023-11-22 21:34:12,991 MainProcess root INFO     Progress: 65%
2023-11-22 21:34:13,114 MainProcess root INFO     Progress: 66%
2023-11-22 21:34:13,235 MainProcess root INFO     Progress: 66%
2023-11-22 21:34:13,393 MainProcess root INFO     Progress: 67%
2023-11-22 21:34:13,510 MainProcess root INFO     Progress: 67%
2023-11-22 21:34:13,632 MainProcess root INFO     Progress: 68%
2023-11-22 21:34:13,752 MainProcess root INFO     Progress: 69%
2023-11-22 21:34:13,877 MainProcess root INFO     Progress: 69%
2023-11-22 21:34:13,997 MainProcess root INFO     Progress: 70%
2023-11-22 21:34:14,114 MainProcess root INFO     Progress: 70%
2023-11-22 21:34:14,232 MainProcess root INFO     Progress: 71%
2023-11-22 21:34:14,349 MainProcess root INFO     Progress: 71%
2023-11-22 21:34:14,468 MainProcess root INFO     Progress: 72%
2023-11-22 21:34:14,586 MainProcess root INFO     Progress: 72%
2023-11-22 21:34:14,704 MainProcess root INFO     Progress: 73%
2023-11-22 21:34:14,824 MainProcess root INFO     Progress: 73%
2023-11-22 21:34:14,944 MainProcess root INFO     Progress: 74%
2023-11-22 21:34:15,065 MainProcess root INFO     Progress: 74%
2023-11-22 21:34:15,184 MainProcess root INFO     Progress: 75%
2023-11-22 21:34:15,307 MainProcess root INFO     Progress: 75%
2023-11-22 21:34:15,426 MainProcess root INFO     Progress: 76%
2023-11-22 21:34:15,553 MainProcess root INFO     Progress: 76%
2023-11-22 21:34:15,676 MainProcess root INFO     Progress: 77%
2023-11-22 21:34:15,795 MainProcess root INFO     Progress: 77%
2023-11-22 21:34:15,909 MainProcess root INFO     Progress: 78%
2023-11-22 21:34:16,026 MainProcess root INFO     Progress: 78%
2023-11-22 21:34:16,144 MainProcess root INFO     Progress: 79%
2023-11-22 21:34:16,261 MainProcess root INFO     Progress: 79%
2023-11-22 21:34:16,379 MainProcess root INFO     Progress: 80%
2023-11-22 21:34:16,499 MainProcess root INFO     Progress: 80%
2023-11-22 21:34:16,597 MainProcess root INFO     Progress: 81%
2023-11-22 21:34:16,712 MainProcess root INFO     Progress: 81%
2023-11-22 21:34:16,828 MainProcess root INFO     Progress: 82%
2023-11-22 21:34:16,932 MainProcess root INFO     Progress: 83%
2023-11-22 21:34:17,049 MainProcess root INFO     Progress: 83%
2023-11-22 21:34:17,170 MainProcess root INFO     Progress: 84%
2023-11-22 21:34:17,289 MainProcess root INFO     Progress: 84%
2023-11-22 21:34:17,371 MainProcess root INFO     Progress: 85%
2023-11-22 21:34:17,490 MainProcess root INFO     Progress: 85%
2023-11-22 21:34:17,610 MainProcess root INFO     Progress: 86%
2023-11-22 21:34:17,729 MainProcess root INFO     Progress: 86%
2023-11-22 21:34:17,813 MainProcess root INFO     Progress: 87%
2023-11-22 21:34:17,931 MainProcess root INFO     Progress: 87%
2023-11-22 21:34:18,051 MainProcess root INFO     Progress: 88%
2023-11-22 21:34:18,134 MainProcess root INFO     Progress: 88%
2023-11-22 21:34:18,253 MainProcess root INFO     Progress: 89%
2023-11-22 21:34:18,374 MainProcess root INFO     Progress: 89%
2023-11-22 21:34:18,467 MainProcess root INFO     Progress: 90%
2023-11-22 21:34:18,579 MainProcess root INFO     Progress: 90%
2023-11-22 21:34:18,699 MainProcess root INFO     Progress: 91%
2023-11-22 21:34:18,797 MainProcess root INFO     Progress: 91%
2023-11-22 21:34:18,888 MainProcess root INFO     Progress: 92%
2023-11-22 21:34:18,995 MainProcess root INFO     Progress: 92%
2023-11-22 21:34:19,084 MainProcess root INFO     Progress: 93%
2023-11-22 21:34:19,191 MainProcess root INFO     Progress: 93%
2023-11-22 21:34:19,307 MainProcess root INFO     Progress: 94%
2023-11-22 21:34:19,394 MainProcess root INFO     Progress: 94%
2023-11-22 21:34:19,501 MainProcess root INFO     Progress: 95%
2023-11-22 21:34:19,586 MainProcess root INFO     Progress: 95%
2023-11-22 21:34:19,707 MainProcess root INFO     Progress: 96%
2023-11-22 21:34:19,794 MainProcess root INFO     Progress: 97%
2023-11-22 21:34:19,909 MainProcess root INFO     Progress: 97%
2023-11-22 21:34:19,992 MainProcess root INFO     Progress: 98%
2023-11-22 21:34:20,110 MainProcess root INFO     Progress: 98%
2023-11-22 21:34:20,196 MainProcess root INFO     Progress: 99%
2023-11-22 21:34:20,281 MainProcess root INFO     Progress: 99%
2023-11-22 21:34:20,355 MainProcess root INFO     Progress: 100%
2023-11-22 21:34:21,712 MainProcess root INFO     Progress: 8%
2023-11-22 21:34:21,899 MainProcess root INFO     Progress: 16%
2023-11-22 21:34:21,901 MainProcess root INFO     Progress: 24%
2023-11-22 21:34:21,902 MainProcess root INFO     Progress: 32%
2023-11-22 21:34:21,910 MainProcess root ERROR    'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
Traceback (most recent call last):
  File "graxpert\gui.py", line 666, in calculate
  File "graxpert\background_extraction.py", line 70, in extract_background
  File "keras\src\saving\saving_api.py", line 238, in load_model
  File "keras\src\utils\traceback_utils.py", line 70, in error_handler
  File "keras\src\utils\traceback_utils.py", line 65, in error_handler
  File "keras\src\saving\legacy\save.py", line 238, in load_model
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
2023-11-22 21:35:48,242 MainProcess root INFO     Progress: 8%
2023-11-22 21:35:48,247 MainProcess root INFO     Progress: 16%
2023-11-22 21:35:48,249 MainProcess root INFO     Progress: 24%
2023-11-22 21:35:48,251 MainProcess root INFO     Progress: 32%
2023-11-22 21:35:48,252 MainProcess root ERROR    'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
Traceback (most recent call last):
  File "graxpert\gui.py", line 666, in calculate
  File "graxpert\background_extraction.py", line 70, in extract_background
  File "keras\src\saving\saving_api.py", line 238, in load_model
  File "keras\src\utils\traceback_utils.py", line 70, in error_handler
  File "keras\src\utils\traceback_utils.py", line 65, in error_handler
  File "keras\src\saving\legacy\save.py", line 238, in load_model
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
2023-11-22 21:35:56,984 MainProcess root INFO     Progress: 8%
2023-11-22 21:35:56,988 MainProcess root INFO     Progress: 16%
2023-11-22 21:35:56,991 MainProcess root INFO     Progress: 24%
2023-11-22 21:35:56,992 MainProcess root INFO     Progress: 32%
2023-11-22 21:35:56,993 MainProcess root ERROR    'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
Traceback (most recent call last):
  File "graxpert\gui.py", line 666, in calculate
  File "graxpert\background_extraction.py", line 70, in extract_background
  File "keras\src\saving\saving_api.py", line 238, in load_model
  File "keras\src\utils\traceback_utils.py", line 70, in error_handler
  File "keras\src\utils\traceback_utils.py", line 65, in error_handler
  File "keras\src\saving\legacy\save.py", line 238, in load_model
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 14: invalid continuation byte

**Comment by Steffenhir** [comment]
Hi, do you have any special characters in your Windows user name like umlaute ä,ü,ö for example?

**Comment by LEMIR13** [comment]
Any idea how to use it ? The v1.0.6dAI worked fine.

**Comment by Steffenhir** [comment]
There is some bug in the tensorflow library we are using with special character such as the "é". I haven't found a solution to this problem yet. A workaround would be to use GraXpert on another user or to rename the current user.

**Comment by schmelly** [comment]
@LEMIR13 we have adressed this issue in GraXpert `2.2.0`. Please let us know if this fixes your issue.

Best regards and CS
David

**Comment by LEMIR13** [comment]
It's working with this last version.
Thanks for this great work !
